### ISSUE TITLE
Retina image support

### ISSUE THREAD

**Issue by ismailuddin** [tuxu/nbviewer-app#5] opened 2018-05-30 09:36 UTC
On Retina screens, there's an option to display inline Matplotlib figures at double resolution so they don't look blurry (https://gist.github.com/minrk/3301035) 

With this option enabled, the figures in notebooks when viewed through this plugin are too big to be seen fully in the preview and also look blurry. 

![screen shot 2018-05-30 at 10 36 59](https://user-images.githubusercontent.com/99201/40712354-69dfdfb6-63f5-11e8-8bf9-653e48c58b29.png)

**Comment by tuxu** [comment] 2018-05-30 11:31
I will look into this. The problem is actually that the metadata stored with the embedded image is ignored in nbviewer.js. This is usually no problem, but for retina images, the metadata contains the width and height for display.

**Comment by tuxu** [comment] 2018-06-10 21:59
Fixed in 43929a71e7951f51176507570105d972adc125cc

**Closed by tuxu** 2018-06-10 21:59 UTC
